//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.15 at 02:14:42 PM MSK 
//


package taxi_by_jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the taxi_by_jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _User_QNAME = new QName("", "User");
    private final static QName _Driver_QNAME = new QName("", "Driver");
    private final static QName _Status_QNAME = new QName("", "Status");
    private final static QName _Passenger_QNAME = new QName("", "Passenger");
    private final static QName _Trip_QNAME = new QName("", "Trip");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: taxi_by_jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Driver }
     * 
     */
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Passenger }
     * 
     */
    public Passenger createPassenger() {
        return new Passenger();
    }

    /**
     * Create an instance of {@link Trip }
     * 
     */
    public Trip createTrip() {
        return new Trip();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "User")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Driver }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Driver")
    public JAXBElement<Driver> createDriver(Driver value) {
        return new JAXBElement<Driver>(_Driver_QNAME, Driver.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Status }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Status")
    public JAXBElement<Status> createStatus(Status value) {
        return new JAXBElement<Status>(_Status_QNAME, Status.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Passenger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Passenger")
    public JAXBElement<Passenger> createPassenger(Passenger value) {
        return new JAXBElement<Passenger>(_Passenger_QNAME, Passenger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Trip }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Trip")
    public JAXBElement<Trip> createTrip(Trip value) {
        return new JAXBElement<Trip>(_Trip_QNAME, Trip.class, null, value);
    }

}
