//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.15 at 02:14:42 PM MSK 
//


package taxi_by_jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Status.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Status">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Created"/>
 *     &lt;enumeration value="Appointed"/>
 *     &lt;enumeration value="In_process"/>
 *     &lt;enumeration value="Excecuted"/>
 *     &lt;enumeration value="Paid_by_driver"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Status")
@XmlEnum
public enum Status {

    @XmlEnumValue("Created")
    CREATED("Created"),
    @XmlEnumValue("Appointed")
    APPOINTED("Appointed"),
    @XmlEnumValue("In_process")
    IN_PROCESS("In_process"),
    @XmlEnumValue("Excecuted")
    EXCECUTED("Excecuted"),
    @XmlEnumValue("Paid_by_driver")
    PAID_BY_DRIVER("Paid_by_driver"),
    @XmlEnumValue("Closed")
    CLOSED("Closed");
    private final String value;

    Status(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Status fromValue(String v) {
        for (Status c: Status.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
